# Generated by Django 6.0.4 on 2026-04-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=60)),
                ('row_number', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=20)),
                ('is_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DemoTicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quota', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DemoVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DemoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=40, unique=True)),
                ('event_name', models.CharField(max_length=120)),
                ('event_datetime', models.CharField(max_length=40)),
                ('order_id', models.CharField(max_length=40)),
                ('customer_name', models.CharField(max_length=120)),
                ('owner_key', models.CharField(default='current_customer', max_length=80)),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Terpakai', 'Terpakai'), ('Dibatalkan', 'Dibatalkan')], default='Valid', max_length=20)),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitur_merah.demoseat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitur_merah.demoticketcategory')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitur_merah.demovenue')),
            ],
        ),
        migrations.AddField(
            model_name='demoseat',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fitur_merah.demovenue'),
        ),
        migrations.AlterUniqueTogether(
            name='demoseat',
            unique_together={('venue', 'section', 'row_number', 'seat_number')},
        ),
    ]
